import { Toaster } from "react-hot-toast";
import Header from "./_components/Header";
import ReservationProvider from "./_components/ReservationContext";
import "./_styles/globals.css";
import { Josefin_Sans } from "next/font/google";

const josefinSans = Josefin_Sans({
  subsets: ["latin"],
  display: "swap",
});
export const metadata = {
  // title: "The Wild Oasis",
  title: {
    template: "%s | The wild Oasis",
    default: "Welcome | The Wild Oasis",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${josefinSans.className} bg-primary-950 text-primary-100 min-h-screen flex flex-col `}
      >
        <Header />
        <div className="flex-1 px-8 py-12 grid">
          <main className="max-w-7xl mx-auto w-full">
            <ReservationProvider>{children}</ReservationProvider>
            <Toaster
              position="top-center" // Customize position
              reverseOrder={false} // Reverse order of toasts
              toastOptions={{
                // Custom styles and behavior
                success: {
                  duration: 3000,
                  style: {
                    background: "#4caf50",
                    color: "#fff",
                  },
                },
                error: {
                  style: {
                    background: "#f44336",
                    color: "#fff",
                  },
                },
              }}
            />
          </main>
        </div>
      </body>
    </html>
  );
}
